# Generated by Django 4.2.5 on 2023-10-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=265)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_post', models.ImageField(blank=True, upload_to='image_post')),
            ],
        ),
    ]
