# Generated by Django 4.2.5 on 2023-10-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
