# Generated by Django 4.2.5 on 2023-10-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0005_alter_comment_name_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=265)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='image_post/')),
            ],
        ),
    ]
