# Generated by Django 4.2.5 on 2023-10-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0006_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=265)),
                ('body', models.TextField()),
                ('date_comment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
