# Generated by Django 4.2.5 on 2023-10-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0012_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
